dark:
  config: i'm dark config

white:
  secret: ${random.uuid}

custom-config:
  used: true
  primary-address: 10.0.2.3
  specific-options:
    main-user: admin
    continents:
    - AFRICA
    - AMERICA
    - EUROPE